services:
  - type: web
    name: hybrid-ai-engine
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: hybrid-ai-engine
      - key: PINECONE_CLOUD
        value: aws
      - key: PINECONE_REGION
        value: us-east-1
      - key: EMBEDDING_DIMENSION
        value: "384"
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: MIN_SAMPLES_TO_TRAIN
        value: "100"
      - key: DEBUG
        value: "False"
